name: frontend_mobile_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  dio: ^5.4.0
  flutter_svg: ^2.0.10+1
  flutter_local_notifications: ^19.5.0
  flutter_fortune_wheel: ^1.3.1
  cached_network_image: ^3.3.1
  intl: ^0.20.2
  equatable: ^2.0.5
  logger: ^2.2.0
  permission_handler: ^12.0.1
  json_annotation: ^4.9.0
  persistent_bottom_nav_bar: ^6.2.1
  flutter_login: ^6.0.0
  image_picker: ^0.8.4+4
  flutter_secure_storage: ^9.2.4
  background_downloader: ^9.2.6
  mobile_scanner: ^7.1.3
  font_awesome_flutter: ^10.12.0
  mocktail: ^1.0.4
  envied: ^1.3.1
  flutter_launcher_icons: ^0.14.4
  qr_flutter: ^4.1.0
  url_launcher: ^6.3.2
  flutter_downloader: ^1.12.0
  infinite_scroll_pagination: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.8.0
  envied_generator: ^1.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/logo.png
